import Head from 'next/head';
import { useState } from 'react';
import Link from 'next/link';





export const getStaticProps = async () => {
  const res = await fetch('https://hammabop-backend.onrender.com/users');
  const data = await res.json();
  return {
    props: { data },
  };
};

export default function Admin({ data }) {
  const [title, setTitle] = useState('');

  function handleSubmit(event) {
    event.preventDefault();

    data(title);
    setTitle('');
  }

  function onChangeTitle(event) {
    setTitle(event.target.value);
  }




  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <div className="otaA">
        {data?.map((el) => {

          return (
            <div key={el._id} className="cardA">


              <Link href={`/aydi/${el._id}`} key={el._id} className='btn'>
                <img className='cart_imga' src={el.image} alt={el.name} />
              </Link>
              <h3>{el.name}</h3>
              <p>{el?.phone}</p>

              <span className='sotib_olish'>
                <p>{el?.price} UZS</p>


              </span>
            </div>
          );
        })}
      </div>
    </>
  );
}
