import axios from 'axios';
import Head from 'next/head';
import { useState } from 'react';

export const getStaticProps = async () => {
  const res = await fetch('https://hammabop-backend.onrender.com/users');
  const data = await res.json();
  return {
    props: { data },
  };
};

export default function Home({ data }) {
  const [name, setName] = useState('');
  const [image, setImage] = useState('');
  const [narxi, setNarxi] = useState();
  const [soni, setSoni] = useState();


  const praductYaratish = (e) => {
    e.preventDefault();
    axios
      .post('https://hammabop-backend.onrender.com/users', {
        name: name,
        image: image,
        quantity: soni,
        price: narxi,
      })
      .then(() => {
        alert('Yaratildi');
        window.location.reload();
      })
      .catch((err) => {
        alert(err);
      });
  };

  const productsDelrte = async (id) => {
    await axios
      .delete(`https://hammabop-backend.onrender.com/users/${id}`)
      .then(() => {
        alert("o'chirildi");
        window.location.reload();
      })
      .catch((err) => {
        alert(err);
      });
  };

   const praductOzgartirish = (_id) => {
    axios
      .patch(`https://hammabop-backend.onrender.com/users/${_id}`, {
        name: name,
        image: image,
        quantity: soni,
        price: narxi,

      })
      .then(() => {
        alert('Ozgartirildi');
        window.location.reload();
      })
      .catch((err) => {
        alert(err);
      });
  };

  return (
    <>
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className='input_sentir'>


          <form className='input_yaratish'
            onSubmit={praductYaratish}>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              type="text"
              placeholder="name"
            />

            <input
              value={image}
              onChange={(e) => setImage(e.target.value)}
              required
              type="text"
              placeholder="image"
            />

            <input
              value={soni}
              onChange={(e) => setSoni(e.target.value)}
              required
              type="text"
              placeholder="soni"
            />
            <input
              value={narxi}
              onChange={(e) => setNarxi(e.target.value)}
              required
              type="number"
              placeholder="narxi"
            />

            <div className='btn'>

              <button className='inbut_btn' type="submit">Yaratish</button>
            </div>
          </form>
        </div>
      </div>
      <div className="otaA">
        {data?.map((el) => {
          return (
            <div key={el._id} className="cardA">
              <img className='card_imgaa' src={el.image} alt={el.name} />
              <h3>{el.name}</h3>
              <p>{el?.phone}</p>

              <p>{el?.price} UZS</p>

              <b>{el?.quantity} ta</b>
              



              <div className="btn_cart">
                <button onClick={() => praductOzgartirish(el?._id)}>o'zgartirish</button>

              </div>
              <br />

            </div>
          );
        })}
      </div>
    </>
  );
}
